# Generated by Django 5.1.3 on 2024-11-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
        ('recipes', '0002_alter_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_recipes', to='common.tag'),
        ),
    ]
