# Generated by Django 5.1.3 on 2024-11-28 20:26

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_picture'),
        ('pictures', '0002_alter_profilepicture_profile'),
        ('recipes', '0003_alter_recipe_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepicture',
            name='recipe',
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('recipe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('is_main', models.BooleanField(blank=True, default=False)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='pictures.gallery')),
            ],
        ),
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
        migrations.DeleteModel(
            name='RecipePicture',
        ),
    ]
