# Generated by Django 5.1.3 on 2024-12-01 09:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_remove_recipepicture_recipe_gallery_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
