# Generated by Django 5.1.3 on 2024-12-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='products',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
